### ISSUE TITLE
Einspielermodus: Schwein kann Viewport verlassen

### ISSUE THREAD

**Issue by FSMaxB** [letsgamedev/spielsklave#1]
Wenn man im Einspielermodus in das Schwein wechselt, dann kann man mit dem Schwein den Viewport (Bildschirm) verlassen.

Zwei Vorschläge, wie man das Problem fixen könnte:
1. Der Viewport bewegt sich mit dem Schwein.
2. Der Viewport bewegt sich nicht mit dem Schwein, das Schwein wird aber daran gehindert den Viewport zu verlassen.

Könnte man auch per Umfrage abstimmen lassen 😁

**Comment by letsgamedev** [comment]
Es gibt sogar noch eine dritte möglichkeit^^Wird teil einer Abstimmung und ist sehr Spielentscheident

**Comment by Siphalor** [comment]
Das Schwein kann übrigens auch die Statue des Spielers aus dem Viewport schieben. 
Das müsste man bei Möglichkeit 2 beachten.

**Comment by Mat2095** [comment]
Wenn das Schwein den Spieler verschiebt und man dann zurückwechselt, springt die Kamera an die neue Stelle. Eine sanfte "Kamerafahrt" wäre angenehmer.

**Comment by letsgamedev** [comment]
@Mat2095 Dein Problem ist ein anderes und müsste demnach in einem anderen Ticket beschrieben werden. also Pro Issue nur ein Problem melden bitte

**Comment by Mat2095** [comment]
@letsgamedev Jup, war irgendwie der Meinung meins wäre eine art "ergänzung". Passt aber nicht, da hab ich wohl nicht genau genug gelesen :|

**Comment by letsgamedev** [comment]
Kamera folgt nun Schwein. Wird auch so bleiben^^

**Comment by FSMaxB** [comment]
Nur so aus Neugierde: Was wäre die dritte Möglichkeit gewesen?
