### ISSUE TITLE
Linker Kartenteil ohne Minimap

### ISSUE THREAD

**Issue by Siphalor** [letsgamedev/spielsklave#100]
Wenn man den Bildschirm nach links verlässt kommt man in einen leicht veränderten Kartenteil. Dort haben erfoorschte Bereiche der Minimap eine einfarbige pinke Textur. 

![img_1788](https://user-images.githubusercontent.com/24505659/27842297-1cd6394e-6109-11e7-87c5-2712c7bae5a2.PNG)

**Comment by letsgamedev** [comment]
Kein Bug, alles in Ordnung^^ Die Map speichert einfach noch nicht und da ist di eminimap von mir noch nicht gezeichnet.
