### ISSUE TITLE
Tastenbelegung suboptimal für manche ergonomische Tastaturen

### ISSUE THREAD

**Issue by FSMaxB** [letsgamedev/spielsklave#101]
Ich habe die Microsoft Sculpt ergonomische Tastatur. Diese hat in der Mitte eine Lücke, jeweils zwischen den Tasten `6` und `7`, `t` und `y`, `g` und `h` sowie `b` und `n`.
Das bedeutet, dass ich zwischen `g`, `h` bzw. `b` und `n` immer zwischen beiden hälften der Tastatur wechseln muss.

Ein anderes Beispiel einer ergonomischen Tastatur mit dieser Eigenschaft ist z.B. auch die Tastatur "Kinesis Freestyle2" und andere.

Ich verstehe wenn das für dich ein Problem ohne relevanz ist, weil es nur wenige Leute betrifft, in dem Fall kannst du diese Issue einfach schließen.

Die simpelste Lösung wäre sich jeweils auf eine hälfte der Tastatur zu beschränken.

Allgemein nützlicher wäre es, die Tasten konfigurierbar zu machen. Muss ja nicht ingame sein, kann auch ein Textfeld im HTML oder ein Dropdown oder so sein.

**Comment by FSMaxB** [comment]
Letzteres würde auch bei anderen Tastaturlayouts helfen.

**Comment by letsgamedev** [comment]
Das stimmt, das Problem ist im Moment noch ohne Relevanz. Da die endgültige Steuerung später selbst festgelegt werden kann. Wann das passiert, weiß ich noch nicht.
