### ISSUE TITLE
Fehlerhafte Raumbetreteanimation.

### ISSUE THREAD

**Issue by EyeBook888** [letsgamedev/spielsklave#102]
Wenn man in das Haus geht, so kommt man unter an der Karte wieder heraus. Anschließend geht der Spieler ein paar Schritte nach oben.
Verlässt man jedoch zuerst die Karte zur rechten Seite und geht dann ins Haus, so geht der Spieler nach unten.

**Comment by letsgamedev** [comment]
Völlig normal. Da ich da noch nicht weiter dran gearbeitet habe. Das sind zwei verschiedene Häuse die unterschiedlich konfigurierte Türen haben.
