### ISSUE TITLE
Grabsteine verschwinden

### ISSUE THREAD

**Issue by tkoebf** [letsgamedev/spielsklave#104]
wenn man nach rechts oder links die Map wechselt, sind die Grabsteine Weg.

**Comment by techel** [comment]
Ist doch nur ne Testmap. Dasselbe Tilemap wird zwar wiederverwendet, allerdings sind die Steine für diese Map nicht in mapdata.js eingetragen.

**Comment by letsgamedev** [comment]
techel hat Recht so ist es, habe ich im Video erwähnt^^
