### ISSUE TITLE
Stein verschwindet nicht wenn er Gegner trifft und gleich wieder eingesammelt wird

### ISSUE THREAD

**Issue by dreadhello** [letsgamedev/spielsklave#105]
Wenn man mit dem Schwein schnell 2x G hintereinander drückt, spuckt das Schwein einen Stein aus und nimmt ihn gleich wieder auf. Wenn man das vor einem Gegner macht, bekommt der Gegner Schaden und der Stein wird trotzdem wieder aufgesaugt, obwohl er verschwinden sollte.

**Comment by letsgamedev** [comment]
Danke dir, werde mich drum kümmern.

**Comment by letsgamedev** [comment]
Sollte mit dem nächsten Update gefixt sein
