### ISSUE TITLE
Lauf animation während der Maptransition 

### ISSUE THREAD

**Issue by Momolem** [letsgamedev/spielsklave#109]
Wenn man versucht zu laufen während die Maptransition (z.B. zwischen oben und mitte), ist die Laufanimation des Spielers aktiv obwohl sich dieser nicht bewegt

**Comment by letsgamedev** [comment]
Das ist absicht und richtet sich an die alten NES und SNES Spiele bei denen oft der gleiche Effekt auftrat :)
