### ISSUE TITLE
Schwein bleibt am Rand hängen

### ISSUE THREAD

**Issue by teccheck** [letsgamedev/spielsklave#11]
Wenn man in Richtung einer Wand läuft und dann zur Seite bleibt das Schwein irgendwann hängen.
![bug](https://cloud.githubusercontent.com/assets/25465306/22481212/aa805c9a-e7f4-11e6-9c78-db02c87d51ca.png)

**Comment by letsgamedev** [comment]
Gleiches Problem hat der Dämon auch. Wäre mit Kreis als Physicbody nicht passiert -.- Mal sehen ob ich da noch was machen kann.

**Comment by letsgamedev** [comment]
Fixed, will be released with new Version.
