### ISSUE TITLE
Lauf-Animation während der Maptransition #2

### ISSUE THREAD

**Issue by T3Daniel** [letsgamedev/spielsklave#111]
Der Spieler läuft immer in seiner Blickrichtung aus der Karte, auch wenn er von einem Gegner geschubst wurde und in die Map schaut.
![transition](https://user-images.githubusercontent.com/44526109/47604671-0b0aa380-d9fd-11e8-9828-b33107e19c25.gif)

**Comment by letsgamedev** [comment]
in der nächsten Version wird die Maptransition nur noch getriggert, wenn der Spiele auch in die Aussenrichtung blickt.
