### ISSUE TITLE
Out of Bounds durch Gegner

### ISSUE THREAD

**Issue by T3Daniel** [letsgamedev/spielsklave#112]
Der Spieler kann sich von einem Gegner in die Wand drängen lassen, sollte er an dieser stehen.
![outofboundsenemy](https://user-images.githubusercontent.com/44526109/47604703-853b2800-d9fd-11e8-94f3-653939ae32b6.gif)

**Comment by letsgamedev** [comment]
Ist mit dem nächsten Update geifxt
