### ISSUE TITLE
Out of Bounds durch doppelte Versteinerung

### ISSUE THREAD

**Issue by T3Daniel** [letsgamedev/spielsklave#113]
Drückt man 'H' während man in der Versteinerungs-Animation ist, springt die Position des Spielers. 
![outofboundsversteinerung](https://user-images.githubusercontent.com/44526109/47604769-45287500-d9fe-11e8-8334-008219cc0f65.gif)

**Comment by letsgamedev** [comment]
Ist in der nächsten Version gefixt
