### ISSUE TITLE
Stein Saug Bug #2

### ISSUE THREAD

**Issue by T3Daniel** [letsgamedev/spielsklave#114]
Das Schwein kann den Stein nicht einsaugen, wenn es nach oben schaut. Mit ein bisschen Vorbereitung kann man das Schwein out of bounds glitchen. Ich nenne es liebevoll das "Schwein-o-pult"
![schweinopult](https://user-images.githubusercontent.com/44526109/47604837-119a1a80-d9ff-11e8-9783-2a566c9acf80.gif)

**Comment by letsgamedev** [comment]
Der Einsaugtrigger wurde von 11 auf 13 Pixel vergrößert, so dass das Schein nun immer eindaugen kann und nicht umhergeschleudert wird^^
