### ISSUE TITLE
Spieler als Statuen form laufen

### ISSUE THREAD

**Issue by Foib** [letsgamedev/spielsklave#115]
Wenn man in der Schlag-Animation ist, dann zum Schwein wechselt um den Spieler zur Statue zu machen und dann wieder den Spieler steuert kann man als Statue laufen. 
https://www.youtube.com/watch?v=oSp5oO4oi-8&feature=youtu.be

**Comment by letsgamedev** [comment]
Ist gefixed. Während des schlagens kann man eine Statue merh werden.
