### ISSUE TITLE
Luft beim Saugen vom Schwein ist relativ zum Schwein

### ISSUE THREAD

**Issue by PucklaJ** [letsgamedev/spielsklave#118]
[![SpindleIssue1](https://img.youtube.com/vi/JICDXiwpReM/0.jpg)](https://www.youtube.com/watch?v=JICDXiwpReM)

Im Video kann man sehen was ich meine. Meiner Meinung nach sollten diese Luftblasen sich nicht mit dem Schwein mitbewegen

**Comment by letsgamedev** [comment]
Saugwolken sind nun in der Welt verankert, nicht im Schwein.
