### ISSUE TITLE
Kleiner Animationsfehler bei Spuckanimation

### ISSUE THREAD

**Issue by PucklaJ** [letsgamedev/spielsklave#119]
[![SpindleIssue2](https://img.youtube.com/vi/QieucSrt8L8/0.jpg)](https://www.youtube.com/watch?v=QieucSrt8L8)

Man kann sehen, dass bei der Spuckanimation des Schweines kurz für ein Frame ein falsches Bild aufblinkt.

**Comment by letsgamedev** [comment]
Nun wird kein falscher Frame mehr angezeigt
