### ISSUE TITLE
Schwein verliert Stein beim Mapwechsel

### ISSUE THREAD

**Issue by TobiasLange1** [letsgamedev/spielsklave#120]
Schritte zum Reproduzieren:
1. Wechsel zum Schwein
2. Sauge Stein neben Spawn auf (oder anderen)
3. Wechsel zum Spieler
4. Nach links gehen (zur anderen Map)

Ist: Stein liegt wieder am Ursprungsort
Soll: Stein bleibt im Schwein

**Comment by letsgamedev** [comment]
Ist so gewollt. Verhindert unsachgemäße Verwendung von Objekten.

**Comment by VatrasCell** [comment]
Sollte dann aber visuell erkenntlich sein, dass es so gewollt ist.
