### ISSUE TITLE
Stein vom Schwein fliegt bis zum nächsten Hindernis

### ISSUE THREAD

**Issue by TobiasLange1** [letsgamedev/spielsklave#122]
Reproduktionsschritte:
1. Zum Schwein wechseln
2. Stein einsaugen
3. Schwein so positionieren, dass sehr lange nichts im Weg ist
4. Stein werfen

Ist: Stein fliegt bis zum nächsten Hindernis (im schlimmsten Fall von den Mapenden von rechts nach links)
Soll: Stein bekommt eine Wurfreichweite.

**Comment by letsgamedev** [comment]
Kein Fehler^^ 
Ob unendlich gespuckt wird oder nicht muss noch entschieden werden.
