### ISSUE TITLE
Stein Collider beim Spucken falsch positioniert

### ISSUE THREAD

**Issue by TobiasLange1** [letsgamedev/spielsklave#123]
Reproduktionsschritte:
1. mit Schwein Stein aufnehmen
2. Wand über Schwein positionieren
3. Stein ausstoßen (Stein kollidiert mit Wand)
4. mit Schwein Stein aufnehmen
5. Wand unter Stein positionieren
6. Stein ausstoßen (Stein fliegt ohne Probleme)

Soll: Stein sollte in 3. und 6. ohne Probleme Fliegen, da Schwein logischerweise größer sein muss als Stein.

**Comment by letsgamedev** [comment]
Ist in der nächsten Version gefixed
