### ISSUE TITLE
Spieler läuft nach Oben 

### ISSUE THREAD

**Issue by BlackBu7let** [letsgamedev/spielsklave#124]
Der Spieler/Char und Das Schwein Laufen nach oben und können nicht mehr aufgehalten werden wenn man ausversehen aus dem Fenster raus ist zum beispiel um dein Video zu sehen , selbst das Wechseln der Chars hat nichts gebracht

**Comment by letsgamedev** [comment]
Kann nicht mehr reproduziert werden von meiner Seite aus.
