### ISSUE TITLE
Schnelles drücken der B und H Tasten lässt Spieler verschwinden.

### ISSUE THREAD

**Issue by TackerTacker** [letsgamedev/spielsklave#125]
Drückt man schnell und wiederholt B und H verschwindet der Spieler. 
Versucht man sich dann zu bewegen kann es passieren das die Kamera (oder Spieler?) sich zum oberen Rand der Karte teleportiert. Es ist mir auch schon passiert das das Schwein ebenfalls verschwunden ist.

**Comment by davibu** [comment]
Kann den Fehler bestätigen.
Bei mir tritt der Fehler auf, wenn h gedrückt wird und bevor die Steinanimation abgelaufen ist b drückt.

**Comment by letsgamedev** [comment]
Ist in der nächsten Version gefixed, Habe vergessen den Swap sicherheitstimer auch beim Hinsetzen zu nutzen.
