### ISSUE TITLE
Schwein Schild Kollision

### ISSUE THREAD

**Issue by davibu** [letsgamedev/spielsklave#127]
Das Schwein "durchstößt" das Schild neben dem Zaun, der Spieler nicht.
![bildschirmfoto vom 2018-12-12 21-14-39](https://user-images.githubusercontent.com/9825602/49896232-08e89100-fe53-11e8-924b-d7e18ce97f7a.png)
![bildschirmfoto vom 2018-12-12 21-15-06](https://user-images.githubusercontent.com/9825602/49896233-08e89100-fe53-11e8-902f-65aecce80d35.png)

**Comment by letsgamedev** [comment]
Ist gefixed, hitbox des Schildes vergrößert, wir bei der nächsten Demo drin sein
