### ISSUE TITLE
Das Stein-Männchen bewegen

### ISSUE THREAD

**Issue by KevinNutellaBReady** [letsgamedev/spielsklave#129]
Wenn man das Schwein ist, und dann den Mensch schiebt, kann man es nicht durch solche Blätter schieben.

**Comment by letsgamedev** [comment]
Was genau sind "Solche Blätter" Die büsche in denen auch die Eier sitzen?

**Comment by KevinNutellaBReady** [comment]
Ja, genau 👍 . Mal ne Frage kannst du mich eig. mal in einem Video grüßen.

**Comment by letsgamedev** [comment]
Da man weder als Spieler noch als Schwein durch die Büsche gehen kann, warum sollte man dann die Statue durch die Büsche schieben können? Das ist so gewollt :)
