### ISSUE TITLE
Luft beim Einsaugen ist zu langsam (Windows 10?)

### ISSUE THREAD

**Issue by PiscesdanAT** [letsgamedev/spielsklave#130]
[Link](https://www.youtube.com/watch?v=DeI-5AdUyYA)
Verglichen mit deinem Video sind hier die Partikel ziemlich langsam.
_Sorry wegen Handyaufnahme, btw._

**Comment by letsgamedev** [comment]
Interessant^^Passiert, das immer oder war das nur ein mal? Also kam das auch nach einem totalen Neustart des Spiels?

**Comment by PiscesdanAT** [comment]
Ja. Seit ich die Version runtergeladen habe. Und ich hab 2 oder 3 mal neu gestartet. war immer so.
Könnte es irgendwie an meinem PC liegen?

**Comment by letsgamedev** [comment]
Kann. Darf aber natürlich eigentlich nicht^^Was hast du denn für ein OS?

**Comment by PiscesdanAT** [comment]
Windows 10. also relativ standard

**Comment by letsgamedev** [comment]
Ja müsste eigentlich gehen. Lassen wir das Ticket erstmal offen und hoffen, dass es in einigen Wochen beim nächsten Release von selbst besser wird^^

**Comment by letsgamedev** [comment]
Luft wird nun korrek schnell eingesaugt, die wolken haben die falsch eupdate funktion genutzt
