### ISSUE TITLE
Schwein saugt ohne Effekt weiter

### ISSUE THREAD

**Issue by Fabian3081** [letsgamedev/spielsklave#132]
Wenn man auf das Schwein wechselt und vor einem Ei saugt, das Schwein getötet wird und das respawnt, ist zwar der Saugeffekt mit den weißen Partikeln weg, aber das Schwein hat immernoch die Animation vom einsaugen.

**Comment by letsgamedev** [comment]
Beim Treffer wird das Schwein nun korrekt in den Idle state gesetzt.
