### ISSUE TITLE
Schwein Animation endet nicht am Zaun

### ISSUE THREAD

**Issue by R3mb0** [letsgamedev/spielsklave#133]
Wenn man zu dem Schild läuft, bei welchem die Box außerhalb des Bildes ist und das Schwein am Zaun hängen bleibt, dann hört die Renn-Animation nicht auf.

**Comment by letsgamedev** [comment]
Also das Schwein rennt weiterhin gegen den Zaun weil es versucht dem Spiele noch zu folgen?

**Comment by R3mb0** [comment]
Ja genau

**Comment by letsgamedev** [comment]
Das ist so gewollt :)
