### ISSUE TITLE
Schwein bleibt im im Haus stecken nachdem man es verlassen hat

### ISSUE THREAD

**Issue by KnuckleJoe96** [letsgamedev/spielsklave#134]
Nachdem ich das Haus verlassen habe und ich mich nicht weiter nach unten bewege (also auch direkt nach links oder rechts bewegen), rutscht das Schwein bei mir in das Haus und bleibt dort stecken. 
![image](https://user-images.githubusercontent.com/18075950/52523314-538a5c00-2c90-11e9-9925-0aef6920bacc.png)

**Comment by davibu** [comment]
Kann ich bestätigen, kann leicht reproduziert werden, wenn man nach dem verlassen des Hauses leicht nach rechts läuft.
Mein Vorschlag wäre, dass das Schwein nach dem Verlassen des Hauses einen weiteren Tile nach vorne geht, bzw. rechts oder links, wenn nach vorne nicht möglich ist.

**Comment by letsgamedev** [comment]
Das Schwein bleibt nun beim betreten der Szene enger bei Dengle und bleibt so nicht mehr oder nicht mehr so schnell stecken.
