### ISSUE TITLE
Steuerungslabel ist zu tief

### ISSUE THREAD

**Issue by x7airworker** [letsgamedev/spielsklave#135]
Das Label "Drücke P um die Steuerung anzuzeigen" verschiebt sich nach unten, nachdem man z.B.: in ein Haus geht.

**Comment by letsgamedev** [comment]
Kann ich nicht reproduzieren bitte um vorher nachher screen schots ein gif oder ein video

**Comment by x7airworker** [comment]
![image](https://user-images.githubusercontent.com/28512986/52535780-be9c6700-2d52-11e9-898b-3dd8bdf7d32a.png)
Also entweder ist mir das erst später aufgefallen und deswegen habe ich das Issue erstellt, oder ich weiß auch nicht. Jedenfalls ist trotzdem das Label zu weit unten.

**Comment by letsgamedev** [comment]
Ah ich verstehe! Ja in dem Fall ist es zu tief, aber eigentlich ist die Textbox zu kurz und darum gab es einen automatischen Zeilenumbruch^^Ist inzwsichen bei mir gefixt
