### ISSUE TITLE
Weltenübergang beim schräg laufen nicht möglich

### ISSUE THREAD

**Issue by jannikgrie** [letsgamedev/spielsklave#137]
Wenn man auf den Weltenübergang schräg zuläuft (also wenn man nach oben oder unten und links oder rechts dückt) funktioniert der Weltenübergang nicht. Wenn man nun dierekt an der Kante steht und geradeaus läuft funktioniert es (trotzdem man gerade läuft) nicht. Man muss erst ein paar Schritte zurück gehen.

**Comment by letsgamedev** [comment]
ist bei mir nun gefixt
