### ISSUE TITLE
Gras weht nach abhacken weiter

### ISSUE THREAD

**Issue by joshi1999** [letsgamedev/spielsklave#139]
Nachdem man das normale durchgehbare Gras abgehackt wurde hüpft es normal hoch und runter, bleibt aber sichtbar und macht weiter mit seiner normalen animation.

Tritt nur bei einem Grass Tile(?) nicht auf:
Wenn man rechts hoch läuft durch den Zaun durch und dann rechts direkt die 4(?) tiles, das oben links verschwindet ganz normal.

**Comment by letsgamedev** [comment]
Gras kann in der nächsten Version korekt abgeschnitten werden. Ist bei mit nun gefixt
