### ISSUE TITLE
Schilder am oberen Rand blenden Textboxen offscreen ein

### ISSUE THREAD

**Issue by bYemma** [letsgamedev/spielsklave#141]
Interagiert man mit einem Schild, das sich am oberen Bildschirmrand befindet, erscheint die Textbox darüber, wodurch sie nicht lesbar ist.

**Comment by DonyThePony** [comment]
![image](https://user-images.githubusercontent.com/18060731/52561380-8dc43c80-2dfb-11e9-8641-b7fa0c54f647.png)
Hier als Screenshot zu sehen.
