### ISSUE TITLE
Schwein bleibt in Saugstellung

### ISSUE THREAD

**Issue by AllAboutVR** [letsgamedev/spielsklave#143]
Servus, hab zwar darüber schon was in #140 gesehen, weiß jetzt aber nicht genau ob es das selbe beschreibt.

Und zwar, wenn ich mit dem Schwein grad am Saugen bin und der Gegner das Schwein tötet dann Spawnt er Saugend wieder und saugt bis ich wieder zum Schwein Wechsel.

Ansonsten, mach weiter so! :D

**Comment by letsgamedev** [comment]
Ja das soll tatsächlich das selbe sein wie in #140 ^^
