### ISSUE TITLE
2 Fehler mit dem Schwein

### ISSUE THREAD

**Issue by EminGani** [letsgamedev/spielsklave#144]
Wenn man während der Sauganimation mit dem Schwein von einem Gegner getroffen wird, bleibt die Sauganimation nach dem Teleport zum Spieler erhalten und das Schwein hört auf einem zu folgen. Dieser Fehler ließ sich bislang immer replizieren.

Des weiteren gibt es hin und wieder das Problem mit der KI, dass die Gegner einem manchmal nicht mehr folgen wenn man den obigen Fehler ausprobiert hat. Dieser Fehler lässt sich aber nicht immer reproduzieren.

**Comment by letsgamedev** [comment]
Wurde bereits mit #143 begradit :)
