### ISSUE TITLE
Glitches beim Schwein

### ISSUE THREAD

**Issue by Siphalor** [letsgamedev/spielsklave#16]
Wenn man im Zweispielermodus die Maus still hält jedoch den Spieler bewegt dann glitcht das Schwein während es sich bewegt dauerhaft ein paar Pixel vor und zurück.

**Comment by letsgamedev** [comment]
Ist behoben, wird demnächst auch online upgedatet.

**Comment by letsgamedev** [comment]
Ups, verwchselt mit issue #18

**Comment by letsgamedev** [comment]
Nun hab ich's aber gefixed. Kommt mit der nächsten Version.
