### ISSUE TITLE
Charakter kann in das wasser gelangen

### ISSUE THREAD

**Issue by justin167** [letsgamedev/spielsklave#18]
wenn man am rechten rand etwa mittig der Map die Pfeiltaste rechts und unten drückt und gleichzeitig schnell hintereinander V (Zum versteinern drückt) gelangt man auf das Wasser.

**Comment by letsgamedev** [comment]
Das geht sogar wenn man nicht schnell V drückt... Wir behoben! hoffe ich.

**Comment by letsgamedev** [comment]
Ist mit meinem nächsten Update behoben.
