### ISSUE TITLE
Schwein grafik bug

### ISSUE THREAD

**Issue by Lauritzof** [letsgamedev/spielsklave#19]
wenn man unten und rechts gleichzeitig drückt bugt die Textur vom Schwein hin und her .
um dies zu lösen kannst du anstat 4 sprites , 8sprites verwenden dann ist es nicht möglich den bug hervorzu rufen

**Comment by letsgamedev** [comment]
Du meinst 8 Sprites im sinne von allen Animationen in allen 8 Bewegungsrichtungen?

**Comment by letsgamedev** [comment]
Problem ist gelöst mit den bisherigen Animationen.
