### ISSUE TITLE
Spieler hört nicht mehr auf in eine Richtung zu gehen

### ISSUE THREAD

**Issue by ImOlli** [letsgamedev/spielsklave#21]
Wenn man mit dem Spieler die ganze Zeit in eine Richtung geht und dann Rechtsklick macht, hört der Spieler nicht mehr auf in diese Richtung zu gehen.

**Comment by letsgamedev** [comment]
Das ist nicht so schlimm. Da am Ende das Spiel nicht im Browser läuft sondern eine normale Desktop-exe wird.
