### ISSUE TITLE
WASD Steuerung

### ISSUE THREAD

**Issue by zhedar** [letsgamedev/spielsklave#24]
Eventuell wäre eine Steuerung mit W,A,S,D zusätzlich zu den Pfeiltasten sinnvoll. Sollte wenig Aufwand sein und würde einem die Verwunderung ersparen, wenn man intuitiv die falsche Steuerung benutzt ;)

**Comment by jonicho** [comment]
Eventuell könnte man auch im Zweispielermodus mit W,A,S,D den Dämon und mit den Pfeiltasten das Schwein steuern.

**Comment by letsgamedev** [comment]
Es war ja gewollt, dass das Schwein mit der Maus zu steuern ist. Sollte sich das im Weiteren Spielverlauf als total doof herausstellen, bekommt das Schwein im Zweispielermodus auch eine Tastensteuerung. WASD und Pfeiltasten bewegen beide nun den Dämon
