### ISSUE TITLE
Zweispielermodus: Schwein prallt nicht von Gegnern ab

### ISSUE THREAD

**Issue by Siphalor** [letsgamedev/spielsklave#25]
Wenn man im Einzelspielermodus mit Schwein oder Dämon gegen die Eier läuft prallt man ab.
Im Zweispielermodus passiert beim Dämon das gleiche, das Schwein kann jedoch auf einmal die Eier, ohne von ihnen abzuprallen, verschieben.

**Comment by letsgamedev** [comment]
Im Zweispielermodus ist es so dass das Schwein wie im Einspielermodus nur schaden nehmen kann, wenn der Dämon zu stein geworden ist. Im Moment ist dies gewolltes verhalten. Darum schließe ich das erstmal.
