### ISSUE TITLE
Fehlende Diagonalbewegung nach Abprallen von Eiern

### ISSUE THREAD

**Issue by Siphalor** [letsgamedev/spielsklave#26]
Wenn der Spieler zwei Pfeiltasten gleichzeitig drückt und sich damit diagonal auf ein Ei zubewegt, bleibt nach dem Abprallen nur noch die Bewegung der zuletzt gedrückten Taste übrig.
Beispiel:
Spieler drückt als erstes rechts, dann zusätzlich noch nach oben. Der Dämon bewegt sich nun schräg nach oben rechts.
Der Dämon trifft auf ein Ei und läuft nur nach oben weiter obwohl noch beide Tasten gedrückt sind.

**Comment by letsgamedev** [comment]
Interessant, kümmere ich mich drum.

**Comment by Siphalor** [comment]
Wenn man die zweite Taste (im Beispiel oben) wieder vor dem Zusammenstoß loslässt, bewegt sich nach dem Abprallen der Spieler übrigens gar nicht mehr.

**Comment by letsgamedev** [comment]
Sollte nun gefixt sein.
