### ISSUE TITLE
Abprall-Animation führt teilweise zum "Fest-Stecken"/Mehrfach-Animation am Spielrand

### ISSUE THREAD

**Issue by nEuDy** [letsgamedev/spielsklave#27]
Mir ist aufgefallen, dass wenn man bereits irgendwo am Ende des Spielrandes steht, und dann an ein Ei stößt oder sogar das Ei dich in Richtung des Spielrandes "drückt", die Abprall-Animation mehrfach ausgelöst wird, und es so aussieht, als ob man in einer Abprall-Schleife "fest steckt".
Ich kann mir vorstellen, dass dies in der späteren Spiele-Entwicklung zu Problemen führen könnte, z.B. wenn man bei Berührung Lebenspunkte abgezogen bekommt, würde man im Falle eines "fest-steckens" sofort mehrfach Lebenspunkte verlieren.

**Comment by letsgamedev** [comment]
Also lieber wenn man bereits im Abprallen ist, kein neues Abprallen zulassen, wenn ich das richtig verstanden habe?

**Comment by nEuDy** [comment]
Hier bin ich leider noch etwas unschlüssig, was der beste Lösungsansatz wäre. Wenn man das mit anderen Spielen wie Zelda vergleicht, blinkt der Spieler ja eine kurze Zeit, da er von einem Gegner berührt wurde und kann somit für eine kurze Zeit nicht nochmal getroffen werden.
Wie du schon gesagt hast, wäre wohl eine Möglichkeit, das Abprallen für einen kurzen Moment nicht mehr zu zulassen, bzw. nicht mehr vom gleichen Ei zu zulassen. In einem "Gerammel" innerhalb des Spielfeldes ist das Abprallen von mehreren Eier ja lustig und bestimmt gewollt :-)
Dies wäre doch ein Ideales Thema für dein kommendes Analyse-LetsPlay von Zelda, wie dort das Spielverhalten ist :-P

**Comment by letsgamedev** [comment]
Ich habe erstmal beschlossen es so zu lassen wie es ist, da im Spiel selbst vorrangig nicht 10 Gegner auf einmal auftauchen werden. Sollte sich das in einem echten Spielszenario als störend erweisen, wird es angepasst.
