### ISSUE TITLE
Schwein kann hinter Hindernissen klemmen

### ISSUE THREAD

**Issue by InDieTasten** [letsgamedev/spielsklave#3]
![image](https://cloud.githubusercontent.com/assets/7047377/22477448/64a91a8a-e7e6-11e6-88d1-8ab3f500f2e4.png)

Der Screenshot erklärt es glaube ich ganz gut. Kann später zu Problemen führen, oder sogar zu einer Mechanik werden.

Version: [8be8654](https://github.com/letsgamedev/spielsklave/tree/8be86548d68c3b405ca3a778c013218cd7b50c52)

**Comment by letsgamedev** [comment]
Wie damit umzugehen ist, wird teil einer Umfrage. Also entweder Schwein mit Pfadsuche oder Schwein gräbt sich bei einem gewissen Abstand zum Spieler (Was lustiger und einfacher ist)

**Comment by letsgamedev** [comment]
Schwein rennt nun durch Hindernisse durch. Wird bald verfeinert.
