### ISSUE TITLE
Wenn man die Steinstatue mit dem Schwein gegen die wand schiebt und dazwischen ein Ei einklemmt wird der Sound immer wiederholt selbst wenn man still steht..

### ISSUE THREAD

**Issue by 0tzkar** [letsgamedev/spielsklave#30]
Das liegt wahrscheinlich daran dass das Ei versucht frei zu kommen es aber nicht schafft.

**Comment by letsgamedev** [comment]
Es sollte mit dem nächsten Upate besser sein. Aber perfekt ist es noch nicht.
