### ISSUE TITLE
Spieler erstarrt nicht vollkommen zu Stein auf Mobilgeräten

### ISSUE THREAD

**Issue by Mat2095** [letsgamedev/spielsklave#31]
Wenn man zum Schwein wechselt bleibt die Animation des Spielers hängen. Er lässt sich aber wie gedacht verschieben. Der Fehler ist bei mir nur auf dem Handy aufgetreten, nicht am Desktop. Dort tritt er aber zuverlässig immer auf.

![screenshot_20170212-202632](https://cloud.githubusercontent.com/assets/11258252/22865333/071763f6-f162-11e6-9d70-3cd1413c7ea9.png)

**Comment by letsgamedev** [comment]
Bug die auf mobilen Geräten aufteten werden nicht berücksichtigt.

**Comment by Mat2095** [comment]
Inzwischen tritt der Fehler übrigens nur noch manchmal auf...
