### ISSUE TITLE
Jesus-Schwein

### ISSUE THREAD

**Issue by projektb** [letsgamedev/spielsklave#32]
Steuert man das Schwein weg von der Statue, so dass zwischen dem Schwein und dem Dämon eine Wasserfläche liegt und drückt dann wieder V, so rennt das Schwein automatisch zurück zum Hauptcharakter und kann dabei übers Wasser gehen.

**Comment by Pilzschaf** [comment]
Gleiches Problem auch bei "Wänden" also den nicht begehbaren Erderhöhungen XD

**Comment by letsgamedev** [comment]
Ist im Moment besser als das Schwein ewig unerreichbar festzuhalten. Genaueres Verhalten kommt in der nächsten Woche. Ist also erstmal kein Bug^^
