### ISSUE TITLE
ungewollte Bewegung

### ISSUE THREAD

**Issue by Ceritak** [letsgamedev/spielsklave#33]
Wenn man im Einzelspieler zur Statue wird dann diese Mit dem Schwein verschiebt, nun mit dem Schwein soweit läuft das die Statue aus dem Bild ist und dann wieder zurückwechselt bewegt sich der Dämon ungewollt.

**Comment by letsgamedev** [comment]
Tatsächlich, aber nur so 2 bis 10 Pixel oder? Werde ich beheben. Hoffe ich.

**Comment by letsgamedev** [comment]
Ist gefixed, kommt mit der nächsten Version.
