### ISSUE TITLE
Framerateeinbruch nach Eischlüpfen + Versteinerung

### ISSUE THREAD

**Issue by HDennemaerker** [letsgamedev/spielsklave#36]
Nach 2-maligem Versteinern oder/und einigen geschlüpften Eiern bricht die Framerate spürbar ein und erholt sich auch nicht mehr.

**Comment by letsgamedev** [comment]
Ich habe die Gegner nun mit einem isFix ausgestattet. Die müssen nun nicht mehr gegen die Tilemap getestet werden. Weiterhin werden die Gegner nur noch jedes Zweite Frame gegen das Tileset getestet. Also immer im Wechsel erst die eine Hälfte, dann die andere.
Bitte mal Cache leeren und testen. FPS sind eingeblendet. Wenns im Mittel über 50 bleibt bin ich zu frieden.
