### ISSUE TITLE
Grüner Punkt (Rückstand in der Spieleranimation)

### ISSUE THREAD

**Issue by SimonNitzsche** [letsgamedev/spielsklave#4]
Wenn du die normale Animation vom Spieler (Wenn der Charakter dich an schaut) ist oben links im eck am Haar ein grüner Punkt vergessen worden.

**Comment by letsgamedev** [comment]
Wird behoben.

**Comment by letsgamedev** [comment]
Behoben, wird mit der nächsten Version veröffentlicht.
