### ISSUE TITLE
den hügel hoch

### ISSUE THREAD

**Issue by Ceritak** [letsgamedev/spielsklave#40]
Hey,
ich bin mir da nicht sicher aber soll man die Eier treffen können wenn man am unteren Hügel steht (den Hügel vor sich) und das Ei ganz am Rand?

**Comment by letsgamedev** [comment]
Ja das ist interessant^^Werde ich vielleicht drauf achten. Könnte aber auch unnötig kompliziert werden.

**Comment by Ceritak** [comment]
Ich bin in Sachen progarmaieren leider noch nicht so drin, aber kannst du nihct in die Kolisionsabfrage ein "wenn Hügel dann Schaden gleich null" einbauen? Musst die Kollision doch eh abfragen, wegen der Bewegung.

**Comment by letsgamedev** [comment]
Im Prinzip ja. Aber eben nur im Prinzip. Manchmal führt das eine zum anderen und auf einmal verbaut man sich alles

**Comment by RicoBrase** [comment]
Man könnte das ganze auch lösen, in dem man "Ebenen" verwendet.

Wenn ich mich recht erinnere, wird das Ganze bei AdvanceMap für GBA Pokemon-ROMs ähnlich gemacht. Dort setzt man die Bewegungsdaten nicht pro Tile im Tileset, sondern manuell auf der Karte (man muss die Map also im Grunde zweimal erstellen). Dafür kann man dann aber auch mit "Höhendaten" arbeiten.

Beispiel: Ein Tile, welches mit "0" markiert ist, ist "ebenendurchlässig", man kann es also von jeder Ebene aus erreichen, um in eine andere Ebene zu gelangen, z.B. für Treppen oder die Sprung-Klippen. Die "1" hingegen wäre ein blockierendes Tile, ist also generell nicht passierbar, auf keiner Ebene. Die "2" wäre ein passierbares Tile auf Ebene 1, etc.

Somit könnte man dann z.B. auch Brücken realisieren, auf denen man oben drüber laufen kann, aber auch unten drunter laufen kann, wenn man die Render-Reihenfolge entsprechend anpasst.

Fügt man dann bei Aktionen wie "Ansprechen" und "Angreifen" noch Ebenen-Abfragen hinzu, könnte man das hier beschriebene Problem lösen (und eventuell noch ein paar zukünftige "Probleme").

Edit: Ich stelle das Ganze nachher (heute abend) mal grafisch dar und packe das Ganze in ein seperaten Issue als Ideenvorschlag. ;)
