### ISSUE TITLE
XBox Controller wird nicht ganz unterstützt.

### ISSUE THREAD

**Issue by nick-strohm** [letsgamedev/spielsklave#41]
Das Spiel unterstützt beim XBox Controller nur 4 Richtungen (Diagonal nicht möglich).

Ich habe [hier](https://github.com/letsgamedev/spielsklave/blob/master/game/js/player.js#L77) eine Überprüfung hinzugefügt, die wenn ein Key gedrückt wird, die Pad-Instanz ausgeben soll. Dies wird auch soweit richtig getan (Tastatur gibt in allen 8 Richtungen eine Ausgabe). Sobald man allerdings beim XBox Controller in eine andere Richtung als Links, Rechts, Oben, Unten lenkt, bekommt man keine weitere Ausgabe und der Spieler bleibt stehen.

**Comment by letsgamedev** [comment]
Im Moment ist das Spiel halt auf meinen Controller hartcoded. Ist also alles normal.
Ich werde mir mal einen 360 Controller ausborgen und dann zusehen, dass der automatisch erkannt wird und dann die Einstellungen geändert werden.

**Comment by nick-strohm** [comment]
@letsgamedev Die Rückgabewerte von ``game.input.gamepad.pad1._axes`` mit einem XBox Controller in den Richtungen Links, Rechts, Oben, Unten sind:
```json
{
  'left': [-1, 0, 0, 0],
  'right': [1, 0, 0, 0],
  'up': [0, -1, 0, 0],
  'down': [0, 1, 0, 0]
}
```

Kombiniert (±):
```json
{
  'topleft': [-0.8, -0.8, 0, 0],
  'topright': [0.8, -0.8, 0, 0],
  'bottomleft': [-0.8, 0.8, 0, 0],
  'bottomright': [0.8, 0.8, 0, 0]
}
```
