### ISSUE TITLE
Spritefehler bei Spiegelung

### ISSUE THREAD

**Issue by Siphalor** [letsgamedev/spielsklave#45]
**(** Wenn sich der Dämon im Wasser spiegelt hat er immer noch das alte Aussehen. 
_Dafür einfach in der player.js Datei in der letzten Funktion alle_ player_ *zu* dengel_ *ändern.* __)__

Außerdem läuft das Spiegelbild auf der Stelle, wenn der Dämon beim Laufen versteinert wird.

**Comment by ImOlli** [comment]
Ich glaube das ist so gewollt das man den alten Spieler sieht...

**Comment by nick-strohm** [comment]
Vielleicht ist das auch nur seine normale Form und ist ein Feature 🤔

**Comment by ImOlli** [comment]
Das glaube ich auch eher

**Comment by letsgamedev** [comment]
Richtig, dass man den alten Char sieht ist gewollt. Die Grafik wird aber noch geändert. Denn die Bewohner sehen ihn als normalen Jungen. Dass der beim zustein werden weitergeht ist natürlich ein Bug^^

**Comment by Siphalor** [comment]
Das erinnert mich ja ein __ganz__ kleines bisschen an Terry Pratchett...  😂

**Comment by pebadd27** [comment]
Das ist kein Bug, das hat Tom im heutigen Video erklärt. Also das mit dem Spiegelbug, das ein anderer Charakter ist :D ;) Link: https://www.youtube.com/watch?v=EmfcxTGbWNk

**Comment by Siphalor** [comment]
Ich weiß, das wurde hier auch schon besprochen (deswegen auch die Klammern).
Der Issue bleibt trotzdem offen wegen des zweiten Teils.

**Comment by letsgamedev** [comment]
Die weitergehende Spielgelanimation ist mit dem nächsten Update behoben.
