### ISSUE TITLE
Schwein: falscher Teleport

### ISSUE THREAD

**Issue by Siphalor** [letsgamedev/spielsklave#46]
Wenn der Dämon versteinert ist und das Schwein gegen ein __leeres__ Nest läuft, dann wird es zum Dämonen zurückteleportiert. Obwohl der Dämon von einem leeren Nest keinen Schaden nimmt. 

Abgesehen davon wäre es vielleicht sinnvoll das Zerstören von Nestern zu deaktivieren, wenn ein Ei darauf steht. Es passiert relativ häufig, dass man in so einer Situation zuschlägt und dann sieht es komisch aus wenn das Ei getroffen wegfliegt __und__ das darunter schwer sichtbare Nest verschwindet.

**Comment by ghost** [comment]
Wenn der Dämon versteinert ist und das Schwein gegen das Ei läuft,
passiert das Selbe.
Nur so als vervollständigung...

**Comment by Siphalor** [comment]
Ich glaube das Teleportieren anstatt Schaden zu nehmen ist Absicht. 
Allerdings gibt es bei den Nestern keinen Grund dafür. Darum geht es bei diesem Bug.

**Comment by letsgamedev** [comment]
Mit dem nächsten Update nimmt das Schwein durch die Büsche keinen Schaden mehr.
