### ISSUE TITLE
Spiegelfehler bei Versteinerung

### ISSUE THREAD

**Issue by ImOlli** [letsgamedev/spielsklave#47]
Wenn der Spieler rechts neben dem Wasser steht und sích dann versteinert. Sieht man für ein paar Frames lang den Spieler im Wasser auf dem Kopf gespiegelt.

![screenshot_2](https://cloud.githubusercontent.com/assets/20519979/23340331/b893142c-fc34-11e6-8790-8596236e3ff4.png)

**Ich habe hier die Frames zum zeigen mal verlangsamt:**
![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/20519979/23340399/d5740690-fc35-11e6-8f7b-1a306789f9fa.gif)

**Comment by letsgamedev** [comment]
Ist mit dem nächsten Update behoben.
