### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ImOlli** [letsgamedev/spielsklave#49]

**Comment by letsgamedev** [comment]
Was sollte denn der Mist bitte?

**Comment by ImOlli** [comment]
Es tut mir außerordentlich leid. Ich hatte einen Spammer programmiert. Um mein Programm zu testen und hatte dann versehentlich diese Seite noch offen. Und dann habe ich aus versehen ganze viele Issues erstellt. Ich habe die Issues auch sofort geclosed und umbenannt da man diese leider nicht mehr löschen kann und ich keine weitere Aufmerksamkeit errichten wollte. Es tut mir wirklich leid. Es wird nicht mehr vorkommen. Es war wirklich dumm von mir... Ich hoffe du hast Verständnis da für.

**Comment by nick-strohm** [comment]
Naja. Hat eher was mit gesundem Menschenverstand und geistiger Reife zu tun. Wenn du einen Penetrationtest oder wie auch immer durchführen willst, dann mach das in einer VM oder abgesicherten Umgebung. Nicht einfach so auf deinem Rechner und selbst wenn, beende davor alle Programme, die von deinen Tests beeinträchtigt werden können. @letsgamedev evtl. kann der GitHub Support die Issues entfernen
