### ISSUE TITLE
'stone_push.wav' wird zu lange abgespielt.

### ISSUE THREAD

**Issue by ghost** [letsgamedev/spielsklave#67]
Wenn man seinen Charakter versteinert und mit dem Schwein den
Dämon kurz gegen irgendein Gegenstand schiebt, spielt sich der 'stone_push.wav' Sound
mehrmals ab (bis zu 3 Mal).

**Comment by Siphalor** [comment]
Mögliches Duplikat zu #30.
Allerdings sieht dieser Issue professioneller aus…

**Comment by letsgamedev** [comment]
Ist mit dem nächsten Update behoben. Allerdings kann das Schiebesoundzeug noch verbessert werden in Zukunft^^
