### ISSUE TITLE
Teleportsound wird nicht abgespielt

### ISSUE THREAD

**Issue by bl4ckscor3** [letsgamedev/spielsklave#68]
Wenn das Schwein, weil es zu weit weg vom Spieler ist, sich zu ihm hinteleportiert, wird kein Teleportsound abgespielt. Beim Teleportieren nachdem der Spieler sich aus seiner Statue befreit wird dieser Sound jedoch abgespielt.

**Comment by letsgamedev** [comment]
Der Sound den man hört ist nicht der Teleportsound sondern der Sound der bröckelnden Statue^^
Es gibt noch keinen Teleportsound.

**Comment by bl4ckscor3** [comment]
Hmm, dieser "wuump"-Sound im Hintergrund hört sich nicht nach einem Zerbröckeln an :/

**Comment by FSMaxB** [comment]
Vielleicht ein Platzhalter-Sound?
