### ISSUE TITLE
Maus-Eingabe tote Winkel

### ISSUE THREAD

**Issue by Mat2095** [letsgamedev/spielsklave#70]
Szenario: man steuert das Schwein per Maus, das Schwein steht an einer Kante, die Maus ist "hinter" der Kante, man bewegt die Maus parallel zur Kante

Erwartetes Verhalten: das Schwein bewegt sich ebenfalls parallel zur Kante, um möglichst nah bei der Maus zu sein

Tatsächliches Verhalten: in einem 45°-Bereich folgt das Schwein nicht

Grafische Veranschaulichung:
![clipboardertemp-14f7a7](https://cloud.githubusercontent.com/assets/11258252/23918969/49132696-08f5-11e7-8a3b-7ff7b2b40a24.png)
Im roten Bereicht folgt das Schwein nicht der Maus.
Entsprechend verhält es sich wenn die Kante oben/links/rechts oder diagonal ist

**Comment by FSMaxB** [comment]
Falls dafür später Path-Finding verwendet wird, wäre das sowieso egal, wenn das jetzt nicht richtig tut.

**Comment by letsgamedev** [comment]
Im Moment ist die Maussteuerung genau die selbe wie die per Tastatur. Es gibt also nur Richtungen aller 45° Gradvielfachen wie auch mit dem Steuerkreuz. Ist also grundsätzlich kein Bug sondern in Moment noch beabsichtigt. Lasse das Ticket aber offen da es nicht so schwer sein sollte das zu ändern. Nur eben erstmal ohne Prio^^
