### ISSUE TITLE
Hängendes Laufen, Feststecken und falsche Teleportationen an Rändern der Map

### ISSUE THREAD

**Issue by Poke714** [letsgamedev/spielsklave#71]
Wenn man am linken/rechten Rand der Map entlang läuft, während man gleichzeitig noch gegen die Wand steuert, hängt der Spieler beim Laufen.

Versteinert man sich an der oberen Wand, kann man sich nicht mehr "entsteinern". Das Schwein läuft dabei durchgehend auf den Spieler zu, bis man die Seite neu lädt.
Wenn man sich an der linken Wand versteinert, findet der Übergang statt und man wird an der anderen Seite der Map in der Wand wieder erscheinen. (Bei der rechten Seite passiert dies nicht)

Hier kann man das als Video sehen:
https://youtu.be/bLHK4ztMDg0

**Comment by letsgamedev** [comment]
Hui das hat mich 4h Arbeit gekostet. Ich habe auch das Zittern beim Laufen wegbekommen. Mit dem nächsten Update sollten die Fehler weg sein.
