### ISSUE TITLE
Dämon bleibt nach rechts/link Übergang stehen

### ISSUE THREAD

**Issue by nEuDy** [letsgamedev/spielsklave#72]
Mir ist in der aktuellen Version v0.10.2 aufgefallen, dass der Dämon während des Laufens trotz gedrückter Pfeiltaste nach rechts/links, unmittelbar nach einem Übergang der Map zum nächsten Bildschirm stehen bleibt und nicht weiter läuft (trotz dauerhaft gedrückter Pfeiltaste in Laufrichtung).
Dies lässt sich wie folgt nachstellen:
1. Laufe rechts oder links aus dem Mapbereich, so dass man über einen Übergang hinweg muss
2. Halte die Lauftaste weiterhin gedrückt, so dass der neue Bereich einmal komplett durchlaufen werden muss
3. Schlage während des Laufens 1x die Sense mit "G"
4. Ist man immer noch im Laufen zum nächsten Übergang und überquert dann den zweiten/nächsten Map-Bereich, bleibt der Dämon nun unmittelbar nach dem Übergang nach links oder rechts einfach stehen, obwohl man immer noch die Lauftaste gedrückt hält

**Comment by letsgamedev** [comment]
Sehr schöner und zuverlässiger Bericht!
