### ISSUE TITLE
Drücken entgegengesetzer oder 3 Pfeiltasten verhindert unterschiedlich andere Eingaben

### ISSUE THREAD

**Issue by Poke714** [letsgamedev/spielsklave#73]
Beim Drücken entgegengesetzer Pfeiltasten oder 3 Pfeiltasten gleichzeitig läuft man nicht mehr in die Richtung, in die man dann eigentlich gehen sollte (z.B. Oben + Unten + Rechts = Rechts). Angreifen und Versteinern funktioniert auch bei manchen Kombinationen nicht oder falsch.
Das Wechseln in den 2-Spielermodus funktioniert immer.
Hier sieht man, was bei welcher Kombination funktioniert und was nicht:

| Gedrückte Tasten 	| Laufen  	| Zu Stein werden 	| Angreifen 	|
|------------------------	|:-------:	|:---------------:	|:----------------------------------------------------------:	|
| Links + Rechts 	| Nein 	| Ja 	| Nein 	|
| Links + Rechts + Oben 	| Nein 	| Ja 	| Nein 	|
| Links + Rechts + Unten 	| Nein 	| Nein 	| Nein 	|
| Oben + Unten 	| Nein 	| Nein 	| Ja 	|
| Oben + Unten + Links 	| Nein 	| Nein 	| Nein 	|
| Oben + Unten + Rechts 	| Nein 	| Nein 	| Ja, pro Angriff bewegt sich der Spieler leicht nach rechts 	|

Oben + Unten + Rechts beim Angreifen:
![aaa](https://cloud.githubusercontent.com/assets/26465699/24075476/a51e2fc4-0c1c-11e7-80ca-359e392a1144.gif)

**Comment by letsgamedev** [comment]
Ein Schwieriges Thema das auch von Tastatur zu Tastatur unterschiedliche Ergebnisse bringt.
Zum Beispiel ist bei mit Links+Recht+angreifen problemlos möglich. Da es sich hier grundsätzlich um konträhe Eingaben handelt, also Links+Recht oder Oben+Unten gleichzeitig, sehe ich das erstmal als nicht kritisch an. Lasse das Ticket aber für einen Späteren Zeitpunk offen.

**Comment by FSMaxB** [comment]
Hängt das mit der Tasten-Matrix der Tastatur zusammen?

**Comment by Poke714** [comment]
Ich habe mit http://www.keyboardtester.com/tester.html ausprobiert, welche Eingaben ankommen. Wenn ich Q und W auf G und H mappe funktioniert jede Kombination mit den Pfeiltasten problemlos. Jedoch bewegt sich bei Oben + Unten + Links/Rechts + Angreifen der Spieler immernoch nach links/rechts, wie man auf der GIF oben sehen kann. Das scheint also ein Problem am Spiel zu sein. Der Rest ist dann kein Problem am Spiel und falls später veränderbare Steuerung da ist könnte man sich das ja dann einfach auf funktionierende Tasten umstellen
