### ISSUE TITLE
Bug mit dem Schwein nach dem Übergang oben/unten

### ISSUE THREAD

**Issue by MrPotatoHead99** [letsgamedev/spielsklave#74]
In der Version 0.10.2 ist mir folgender Bug aufgefallen:
Beim Übergang der Map von oben nach unten glicht das Schwein durch die Bäume, wenn dieses vor dem Übergang an einem Baum hängen bleibt.
Im Singleplayer sieht das wie auf den Bildern gezeigt aus, im Multiplayer läuft das Schwein durch die Bäume.
![1](https://cloud.githubusercontent.com/assets/26169092/24301070/d268bde6-10ae-11e7-8560-cae4398c70fb.PNG)
![2](https://cloud.githubusercontent.com/assets/26169092/24301083/da24419a-10ae-11e7-84e4-e9bd6d19826e.PNG) 
![3](https://cloud.githubusercontent.com/assets/26169092/24301086/dca23350-10ae-11e7-8156-8c9773eef1c2.PNG) [Das Schwein läuft so lange "auf" dem Baum, bis der Spieler sich weiter davon entfernt]

**Comment by letsgamedev** [comment]
Ist im nächsten Update behoben. Das Schwein gleitet beim Übergang zum Spieler
