### ISSUE TITLE
Sichel unter Grabstein sichtbar

### ISSUE THREAD

**Issue by fewieden** [letsgamedev/spielsklave#77]
Wenn man den Charakter direkt hinter einen Grabstein stellt und mit der Sichel einen Schwung durchführt, dann ist die Sichel ein paar Pixel unter dem Grabstein sichtbar.

**Comment by letsgamedev** [comment]
Was wäre die alternative?

**Comment by Siphalor** [comment]
Vielleicht lässt es sich ja vermeiden so kleine Collision-Boxes für Objekte zu verwenden...

**Comment by letsgamedev** [comment]
Das habe ich leider nicht verstanden, kannst du das mit bildern verdeutlichen?

**Comment by fewieden** [comment]
Die collision box hinter dem Grabstein um die benötigten Pixel erhöhen, sodass er nicht mehr so nah ran gehen kann.

![](https://i.imgur.com/Rr87fU5.png)

**Comment by letsgamedev** [comment]
Hm nee das halte ich nicht für dienlich. Ich denke dass wir eher damit leben werden.
