### ISSUE TITLE
Schwein im Baum

### ISSUE THREAD

**Issue by FerbFloo** [letsgamedev/spielsklave#79]
Wenn man im oberen Teil den Mehrspielermodus betritt, das Schwein in die Ecke unten rechts steuert und dann nach unten, in den anderen Teil geht, buggt das Schwein in einem Baum. Screenshot habe ich nicht, aber ich denke, du glaubst mir auch so...

**Comment by letsgamedev** [comment]
Ich kanns überhaupt nicht reproduzieren. Wenn ich im oberen Chunk bin dann das Schwein mit der Maus nach unten Recht steuere und dann mit dem Spieler in den unteren Chunk gehe, wird das Schwein zum Spiele gezogen und das Schwein ist nach dem Übergang beim Spieler.
