### ISSUE TITLE
Die Textur ist weg...

### ISSUE THREAD

**Issue by FerbFloo** [letsgamedev/spielsklave#80]
Im neuesten Update fehlt (am Handy) die Textur von einem der Buttons oben.
Screenshot:
https://www.dropbox.com/s/co090fop6lyxt9m/Bug.png?dl=0

**Comment by Siphalor** [comment]
Das ist bisher noch Absicht:
Die Texturen der Buttons werden bloß eingeblendet, wenn nötig.
Dass heißt beim Spieler `B` fürs Hinsetzen und beim Schwein kein `G` fürs Schlagen.

**Comment by letsgamedev** [comment]
Genau^^
