### ISSUE TITLE
Sitzendes Scwein kann laufen?!

### ISSUE THREAD

**Issue by FerbFloo** [letsgamedev/spielsklave#81]
Wenn du das Schwein hinsetzt und in den anderen Abteil gehst wird das sitzende Schwein mitgezogen... Das sieht mir nicht sehr richtig aus (getestet am Handy)

**Comment by letsgamedev** [comment]
Ah gut, Dann muss das Schwein natürlich wieder aufstehen^^

**Comment by letsgamedev** [comment]
Ist in der nächsten Version gefixt
