### ISSUE TITLE
Grabsteine sind undefiniert

### ISSUE THREAD

**Issue by FerbFloo** [letsgamedev/spielsklave#82]
Am Handy steht auf allen Grabsteinen "undifined"

**Comment by FerbFloo** [comment]
https://www.dropbox.com/s/ctflyak7f95ydic/Foto%2001.04.17%2C%2017%2028%2053.png?dl=0

**Comment by Siphalor** [comment]
Tritt nur am Handy auf, solche Bugs sind hier im Allgemeinen nicht wichtig...

**Comment by letsgamedev** [comment]
Könnte mit dem nächsten Update besser sein. Wenn von Handy gesprochen wird, ist es immer besser Android oder iOS anzugeben. iOS wird auf jeden fall Probleme haben. Am Ende wird das Spiel in einer Chromiumumgebung laufen. Also sind die wichtigsten Bugs die, die unter Chrome passieren.
