### ISSUE TITLE
Spiegelung zittert

### ISSUE THREAD

**Issue by KeKsBoTer** [letsgamedev/spielsklave#83]
Wenn man nach unten und in eine Richtung gegen den rand eines Wassers läuft, zittert die Spieglung.

**Comment by Siphalor** [comment]
Bei mir zittert das Spiegelbild nur so sehr wie die Spielfigur beim normalen Laufen sowieso "zittert" (also sich durch die Gehbewegung auf- und abbewegt).

**Comment by letsgamedev** [comment]
Fittern ist in der nächsten Version behoben. Auch beim Schwein.
