### ISSUE TITLE
Schwein kann Statue durch den Grabstein schieben

### ISSUE THREAD

**Issue by DerDenkbefreite** [letsgamedev/spielsklave#85]
Ich habe herausgefunden, dass es möglich ist, den Spieler im versteinerten Zustand mit dem Schwein durch einen Grabstein durchzuschieben. Anscheinend kolldiert er mit diesen nicht. Da man mit dem Spieler auch nicht durchkommt, wäre es sinnvoller, wenn auch die Statue mit den Grabsteinen kollidieren würde.

Hoffe, ich konnte helfen

**Comment by letsgamedev** [comment]
Ist in der nächsten Version gefixt. War natürlich ein Fehler von mir^^
