### ISSUE TITLE
Textboxanimation passiert ab und zu nicht.

### ISSUE THREAD

**Issue by FerbFloo** [letsgamedev/spielsklave#87]
Am PC übertritt die Welcome Message die Border... Ist zwar immer noch lesbar aber nicht so schön

PS: Das Schwein ist bei mir jetzt nicht mehr im Baum, so wie bei dir... Wunderheilung?!?!

**Comment by letsgamedev** [comment]
Da bitte ich dringlichst um einen Screenshot und welcher Browser verwendet wird.

**Comment by Siphalor** [comment]
Bei mir sieht es am iPhone mit Safari so aus:
![img_1559](https://cloud.githubusercontent.com/assets/24505659/24548853/f8207fac-1616-11e7-89a6-80e6c5398542.PNG)

Computer habe ich noch nicht wieder ausprobiert.

**Comment by letsgamedev** [comment]
Ja woran das genau liegt weiß ich nicht. Das passiert in Chrome auch ab und zu.

**Comment by letsgamedev** [comment]
Okay nun habe ichs verstanden. Das mit zulang nach UNTEN zu lang bedeutet^^Das liegt daran dass  der Textbox Tween manchmal nicht geht.
