### ISSUE TITLE
Schwein Grafik Fehler?

### ISSUE THREAD

**Issue by ChangeCraft** [letsgamedev/spielsklave#89]
Bei mir ist manchmal, wenn das Schwein stehen bleibt, der Mund vom Schwein etwas komisch. Liegt das am Browser oder an dem Spiel? 
![screenshot_4](https://cloud.githubusercontent.com/assets/23432314/24628503/d84c814c-18b6-11e7-93a0-1518254fb32b.png)

**Comment by letsgamedev** [comment]
Schwer zu sagen. Eher am Browser da das Spiel ja keine solche Subpixel zulässt.
