### ISSUE TITLE
Schwein bleibt im Baum stecken :/

### ISSUE THREAD

**Issue by Chrisinator87** [letsgamedev/spielsklave#90]
Hallo!

Hab gerade herausgefunden das man an der einen gezeigten Ecke das Schwein in ein Baum buggen kann.
Wenn man mit dem Dämon etwas weiter weg geht löst sich das Problem zwar von alleine aber trotzdem dachte ich ich zeige euch das mal :p

Link: https://www.youtube.com/watch?v=zf7lJd5YM6E&feature=youtu.be

**Comment by letsgamedev** [comment]
"Dieses Video ist nicht verfügbar" vielleicht auf Privat?

**Comment by Chrisinator87** [comment]
Sorry habe es gefixt :D

**Comment by letsgamedev** [comment]
Ah serh gut, ja nun habe ich es verstanden^^

**Comment by letsgamedev** [comment]
Ist im nächsten Update behoben
