### ISSUE TITLE
"Freeze" beim Spammen von G und N vor Schild

### ISSUE THREAD

**Issue by derkalaender** [letsgamedev/spielsklave#91]
Der "Freeze" geschieht dann, wenn man die Taste zum Angriff und gleichzeitig die zum Lesen vor einem Schild spammt. Ich schätze es liegt daran, dass das das Spiel versucht, den Text zu lesen, während allerdings die Angriffs-Animation noch abgespielt wird, wodurch sich das Spiel vermutlich mit den Animation-States durcheinander kommt.

Dieses Problem ist früher schon einmal aufgetaucht, wenn man zu schnell zwischen Mensch und Schwein gewechselt hat (wurde allerdings schon wieder gefixt). Ich empfehle dir, irgendetwas einzubauen, dass sowas gar nicht mehr passieren kann, irgendwas, dass dafür sorgt, dass nicht mehrere Animationen beim Spieler gleichzeitig ausgeführt werden können!

Danach kann man sich nicht mehr wirklich bewegen und auch keine Aktionen mehr ausführen. Schaden durch Gegner nimmt man allerdings immer noch und man kann sterben, wobei dann alles wieder normal ist

Ich habe [hier](https://youtu.be/a8VyYVzlWQA) auch ein kleines Video, welches den Bug zeigt!

**Comment by letsgamedev** [comment]
Ist mit dem nächsten Update behoben.
