### ISSUE TITLE
Fehlerhafte Wasser-Spiegelung beim Schwein

### ISSUE THREAD

**Issue by derkalaender** [letsgamedev/spielsklave#92]
Wenn man nur das Schwein spielt und dann an/gegen Wasser läuft und dann B zum Hinsetzen drückt, während man noch eine Pfeiltaste drückt, wird weiterhin die Animation fürs Laufen bei der Wasser-Spiegelung abgespielt

**Comment by letsgamedev** [comment]
ist mit dem nächsten Update behoben
