### ISSUE TITLE
Ei verschwindet während Schwenk von Abteil zu Abteil

### ISSUE THREAD

**Issue by niklasschroetler** [letsgamedev/spielsklave#93]
Wenn man im unteren "Abteil" (Welt-Teil) das Ei links vom Übergang schlägt, ist es möglich, das dies in den Übergangs-Part läuft. Läuft man zu ihm bewegt sich die Kamera vom einen Abteil ins andere, wobei das Ei während dem Schwenk plötzlich verschwindet. Geht man zurück ins andere Abteil ist es wieder an seinem Ursprungsplatz. 
Das mit dem "am Ursprungsplatz sein" stört nicht so sehr, aber es sieht unschön aus, dass as Ei im Schwenk verschwindet.

**Comment by letsgamedev** [comment]
Ist mit dem nächsten Update behoben. Es kann aber noch passieren, der der "kopf" des eis früberschaut und dann verschwindet. Ist aber vorerst okay so
